import { Base } from "@/src/lib/types/base";

export const NUMBER_SYSTEMS = [
    { value: "10", label: "numbersystem.decimal", name: "Decimal (Base 10)" },
    { value: "2", label: "numbersystem.binary", name: "Binary (Base 2)" },
    { value: "8", label: "numbersystem.octal", name: "Octal (Base 8)" },
    { value: "16", label: "numbersystem.hexadecimal", name: "Hexadecimal (Base 16)" },
    { value: "3", label: "numbersystem.ternary", name: "Ternary (Base 3)" },
    { value: "4", label: "numbersystem.quaternary", name: "Quaternary (Base 4)" },
    { value: "5", label: "numbersystem.quinary", name: "Quinary (Base 5)" },
    { value: "6", label: "numbersystem.senary", name: "Senary (Base 6)" },
    { value: "7", label: "numbersystem.septenary", name: "Septenary (Base 7)" },
    { value: "9", label: "numbersystem.nonary", name: "Nonary (Base 9)" },
    { value: "11", label: "numbersystem.undecimal", name: "Undecimal (Base 11)" },
    { value: "12", label: "numbersystem.duodecimal", name: "Duodecimal (Base 12)" },
    { value: "13", label: "numbersystem.tridecimal", name: "Tridecimal (Base 13)" },
    { value: "14", label: "numbersystem.tetradecimal", name: "Tetradecimal (Base 14)" },
    { value: "15", label: "numbersystem.pentadecimal", name: "Pentadecimal (Base 15)" },
    { value: "17", label: "numbersystem.heptadecimal", name: "Heptadecimal (Base 17)" },
    { value: "18", label: "numbersystem.octodecimal", name: "Octodecimal (Base 18)" },
    { value: "19", label: "numbersystem.enneadecimal", name: "Enneadecimal (Base 19)" },
    { value: "20", label: "numbersystem.vigesimal", name: "Vigesimal (Base 20)" },
    { value: "21", label: "numbersystem.unvigesimal", name: "Unvigesimal (Base 21)" },
    { value: "22", label: "numbersystem.duovigesimal", name: "Duovigesimal (Base 22)" },
    { value: "23", label: "numbersystem.trivigesimal", name: "Trivigesimal (Base 23)" },
    { value: "24", label: "numbersystem.tetravigesimal", name: "Tetravigesimal (Base 24)" },
    { value: "25", label: "numbersystem.pentavigesimal", name: "Pentavigesimal (Base 25)" },
    { value: "26", label: "numbersystem.hexavigesimal", name: "Hexavigesimal (Base 26)" },
    { value: "27", label: "numbersystem.heptavigesimal", name: "Heptavigesimal (Base 27)" },
    { value: "28", label: "numbersystem.octovigesimal", name: "Octovigesimal (Base 28)" },
    { value: "29", label: "numbersystem.enneavigesimal", name: "Enneavigesimal (Base 29)" },
    { value: "30", label: "numbersystem.trigesimal", name: "Trigesimal (Base 30)" },
    { value: "31", label: "numbersystem.untrigesimal", name: "Untrigesimal (Base 31)" },
    { value: "32", label: "numbersystem.duotrigesimal", name: "Duotrigesimal (Base 32)" },
    { value: "33", label: "numbersystem.tritrigesimal", name: "Tritrigesimal (Base 33)" },
    { value: "34", label: "numbersystem.tetratrigesimal", name: "Tetratrigesimal (Base 34)" },
    { value: "35", label: "numbersystem.pentatrigesimal", name: "Pentatrigesimal (Base 35)" },
    { value: "36", label: "numbersystem.hexatrigesimal", name: "Hexatrigesimal (Base 36)" },
] as const;

export const DEFAULT_NUMBER_SYSTEM = "10";
export const DEFAULT_TWICE_NUMBER_SYSTEM = "2";

export const NUMERAL_VALUE_DICTIONARY: Record<string, number> = {
    "0": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    A: 10,
    B: 11,
    C: 12,
    D: 13,
    E: 14,
    F: 15,
    G: 16,
    H: 17,
    I: 18,
    J: 19,
    K: 20,
    L: 21,
    M: 22,
    N: 23,
    O: 24,
    P: 25,
    Q: 26,
    R: 27,
    S: 28,
    T: 29,
    U: 30,
    V: 31,
    W: 32,
    X: 33,
    Y: 34,
    Z: 35,
};

export const NUMERAL_NAME_TO_LINGUISTIC_NAME: Record<string, string> = {
    "10": "decimal",
    "2": "binary",
    "8": "octal",
    "16": "hexadecimal",
    "3": "ternary",
    "4": "quaternary",
    "5": "quinary",
    "6": "senary",
    "7": "septenary",
    "9": "nonary",
    "11": "undecimal",
    "12": "duodecimal",
    "13": "tridecimal",
    "14": "tetradecimal",
    "15": "pentadecimal",
    "17": "heptadecimal",
    "18": "octodecimal",
    "19": "enneadecimal",
    "20": "vigesimal",
    "21": "unvigesimal",
    "22": "duovigesimal",
    "23": "trivigesimal",
    "24": "tetravigesimal",
    "25": "pentavigesimal",
    "26": "hexavigesimal",
    "27": "heptavigesimal",
    "28": "octovigesimal",
    "29": "enneavigesimal",
    "30": "trigesimal",
    "31": "untrigesimal",
    "32": "duotrigesimal",
    "33": "tritrigesimal",
    "34": "tetratrigesimal",
    "35": "pentatrigesimal",
    "36": "hexatrigesimal",
};

export const LINGUISTIC_NAME_TO_NUMERAL_NAME: Record<string, Base> = {
    decimal: "10",
    binary: "2",
    octal: "8",
    hexadecimal: "16",
    ternary: "3",
    quaternary: "4",
    quinary: "5",
    senary: "6",
    septenary: "7",
    nonary: "9",
    undecimal: "11",
    duodecimal: "12",
    tridecimal: "13",
    tetradecimal: "14",
    pentadecimal: "15",
    heptadecimal: "17",
    octodecimal: "18",
    enneadecimal: "19",
    vigesimal: "20",
    unvigesimal: "21",
    duovigesimal: "22",
    trivigesimal: "23",
    tetravigesimal: "24",
    pentavigesimal: "25",
    hexavigesimal: "26",
    heptavigesimal: "27",
    octovigesimal: "28",
    enneavigesimal: "29",
    trigesimal: "30",
    untrigesimal: "31",
    duotrigesimal: "32",
    tritrigesimal: "33",
    tetratrigesimal: "34",
    pentatrigesimal: "35",
    hexatrigesimal: "36",
};

export const DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
